name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Use Node.js 24
      uses: actions/setup-node@v5
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      run: pnpm build

    - name: Test
      run: pnpm test
